#!/usr/bin/env bash
set -Eeuo pipefail

wizard_banner() {
  local ver="unknown"
  [[ -r "$ROOT_DIR/VERSION" ]] && ver="$(tr -d '[:space:]' < "$ROOT_DIR/VERSION")"
  cat <<EOF2
============================================================
                     VPS Init ${ver}
============================================================
用途：用于 VPS 自动化初始化、配置与验收。

推荐在全新 Ubuntu 24.04 LTS VPS 上运行。
EOF2
}

wizard_select() {
  local prompt="$1"; shift
  local reply
  while true; do
    echo "$prompt" >&2
    local i=1 opt
    for opt in "$@"; do printf '  %d. %s\n' "$i" "$opt" >&2; i=$((i+1)); done
    read -r -p "请选择 [1-$#]: " reply
    [[ "$reply" =~ ^[0-9]+$ ]] && (( reply >= 1 && reply <= $# )) && { printf '%s\n' "$reply"; return 0; }
    echo "输入无效，请重新选择。" >&2
  done
}

wizard_yesno() {
  local prompt="$1" default="${2:-y}" reply
  if [[ "$default" == y ]]; then
    read -r -p "$prompt [Y/n]: " reply; reply="${reply:-y}"
  else
    read -r -p "$prompt [y/N]: " reply; reply="${reply:-n}"
  fi
  [[ "$reply" =~ ^[Yy]$ ]]
}

wizard_prompt_default() {
  local prompt="$1" default="${2:-}" reply
  if [[ -n "$default" ]]; then
    read -r -p "$prompt [$default]: " reply
    printf '%s\n' "${reply:-$default}"
  else
    read -r -p "$prompt: " reply
    printf '%s\n' "$reply"
  fi
}

wizard_detect_ssh_port() {
  local p=""
  if [[ -n "${SSH_CONNECTION:-}" ]]; then
    p="$(awk '{print $4}' <<<"$SSH_CONNECTION" 2>/dev/null || true)"
  fi
  if ! [[ "$p" =~ ^[0-9]+$ ]] || ((p < 1 || p > 65535)); then
    p="$(sshd -T 2>/dev/null | awk '/^port /{print $2; exit}' || true)"
  fi
  [[ "$p" =~ ^[0-9]+$ ]] || p=22
  printf '%s\n' "$p"
}

wizard_existing_ed25519_key() {
  [[ -r /root/.ssh/authorized_keys ]] || return 1
  awk '$1=="ssh-ed25519" {print; exit}' /root/.ssh/authorized_keys
}

wizard_shell_quote_value() {
  # config.env is sourced by bash; %q safely represents arbitrary single-line values.
  printf '%q' "$1"
}

wizard_write_config() {
  local dst="$1"
  umask 077
  cat > "$dst" <<EOF2
# Generated by VPS Init interactive wizard.
# You may edit this file and rerun: vps-init apply "$dst"
PROFILE=$(wizard_shell_quote_value "$W_PROFILE")
PROVIDER=$(wizard_shell_quote_value "$W_PROVIDER")
SERVER_NAME=$(wizard_shell_quote_value "$W_SERVER_NAME")
SSH_PORT=$(wizard_shell_quote_value "$W_SSH_PORT")
SSH_PUBLIC_KEY=$(wizard_shell_quote_value "$W_SSH_PUBLIC_KEY")
SSH_IDENTITY_HINT=$(wizard_shell_quote_value "$W_SSH_IDENTITY_HINT")
ROOT_DOMAIN=$(wizard_shell_quote_value "$W_ROOT_DOMAIN")
DNS_PROVIDER="cloudflare"
LE_EMAIL=$(wizard_shell_quote_value "$W_LE_EMAIL")
PANEL_DOMAIN_OVERRIDE=""
NODE_DOMAIN_OVERRIDE=""
REALITY_TARGET_MODE=$(wizard_shell_quote_value "$W_REALITY_TARGET_MODE")
REALITY_TARGET=$(wizard_shell_quote_value "$W_REALITY_TARGET")
REALITY_CANDIDATES="dl.google.com,www.apple.com,www.microsoft.com,github.io"
ENABLE_SUBSCRIPTION="auto"
SUBSCRIPTION_EXPOSE_MODE="auto"
SUBSCRIPTION_PORT=$(wizard_shell_quote_value "$W_SUBSCRIPTION_PORT")
XUI_PANEL_URI_PATH=$(wizard_shell_quote_value "$W_PANEL_PATH")
XUI_SUB_URI_PATH=$(wizard_shell_quote_value "$W_SUB_PATH")
ENABLE_DOCKER=$(wizard_shell_quote_value "$W_ENABLE_DOCKER")
ENABLE_CF_WS="false"
ENABLE_CF_PREFERRED="false"
ENABLE_CLOUDFLARESUB="false"
EOF2
  chmod 600 "$dst"
}

wizard_collect_ssh_key() {
  W_SSH_IDENTITY_HINT=""
  local existing choice provider_slug ipcompact keyname pasted
  existing="$(wizard_existing_ed25519_key || true)"
  if [[ -n "$existing" ]]; then
    echo
    echo "检测到 root 已有 ED25519 authorized_keys："
    ssh-keygen -lf <(printf '%s\n' "$existing") 2>/dev/null || true
    if wizard_yesno "直接使用现有公钥？" y; then
      W_SSH_PUBLIC_KEY="$existing"
      return 0
    fi
  fi

  choice="$(wizard_select $'SSH 公钥：\n  推荐使用 ED25519。' \
    "粘贴已有 ssh-ed25519 公钥" \
    "显示 Windows PowerShell 生成命令，然后回来粘贴")"
  if [[ "$choice" == 2 ]]; then
    provider_slug="$(printf '%s' "${W_PROVIDER:-vps}" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9_-')"
    [[ -n "$provider_slug" ]] || provider_slug="vps"
    ipcompact="${W_SERVER_IP//./}"
    keyname="id_ed25519_${provider_slug}_${ipcompact}"
    W_SSH_IDENTITY_HINT="$keyname"
    cat <<EOF2

请在你自己的 Windows PowerShell 另开窗口执行：

ssh-keygen -t ed25519 -f "\$env:USERPROFILE\\.ssh\\${keyname}" -C "${provider_slug}-${W_SERVER_IP}"
Get-Content "\$env:USERPROFILE\\.ssh\\${keyname}.pub" | Set-Clipboard

只需要复制 .pub 公钥，绝对不要上传私钥。
EOF2
  fi
  while true; do
    read -r -p "现在粘贴完整 ssh-ed25519 公钥: " pasted
    if [[ "$pasted" == ssh-ed25519\ * ]]; then
      local tmp
      tmp="$(mktemp)"; printf '%s\n' "$pasted" > "$tmp"
      if ssh-keygen -l -f "$tmp" >/dev/null 2>&1; then rm -f "$tmp"; W_SSH_PUBLIC_KEY="$pasted"; return 0; fi
      rm -f "$tmp"
    fi
    echo "这不是可解析的 ssh-ed25519 公钥，请重新粘贴。"
  done
}

wizard_collect() {
  require_root
  [[ -t 0 ]] || die "交互向导需要 TTY。"
  if ! command_exists curl; then
    wait_apt_lock 300
    apt-get update -qq
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq curl ca-certificates
  fi
  wizard_banner
  echo

  local mode_choice profile_choice current_port custom="false"
  mode_choice="$(wizard_select "安装方式：" "快速安装（推荐，只问必要项目）" "自定义安装")"
  [[ "$mode_choice" == 2 ]] && custom="true"

  profile_choice="$(wizard_select "请选择部署模式：" \
    "Base Only - 系统初始化/安全/BBR/Swap，不安装 3x-ui" \
    "Reality Only - 3x-ui + Reality + IP HTTPS 订阅，不需要域名" \
    "Nginx + Reality - Nginx Stream 443 分流，需要 Cloudflare 域名" \
    "Lucky + Reality - Reality 占 443，HTTPS fallback 到 Lucky，需要 Cloudflare 域名")"
  case "$profile_choice" in
    1) W_PROFILE="base-only" ;;
    2) W_PROFILE="reality-only" ;;
    3) W_PROFILE="nginx-reality" ;;
    4) W_PROFILE="lucky-reality" ;;
  esac
  state_load
  if [[ -n "${DEPLOYED_PROFILE:-}" && "$DEPLOYED_PROFILE" != "$W_PROFILE" ]]; then
    echo "这台 VPS 已部署 Profile=${DEPLOYED_PROFILE}。"
    echo "为避免改变 443/TLS 拓扑，向导不会把它自动切换为 ${W_PROFILE}。"
    echo "如需换 Profile，建议新 VPS 或按 RUNBOOK 手工迁移。"
    return 11
  fi

  W_SERVER_IP="$(get_public_ipv4 || true)"
  [[ -n "$W_SERVER_IP" ]] || die "无法检测公网 IPv4。"
  echo
  echo "检测到公网 IPv4：$W_SERVER_IP"

  W_PROVIDER="$(wizard_prompt_default "VPS 服务商（只用于密钥命名/报告，例如 racknerd、vmiss）" "vps")"
  W_SERVER_NAME="$(wizard_prompt_default "这台 VPS 的名称（可留空）" "${W_PROVIDER}-${W_SERVER_IP}")"
  current_port="$(wizard_detect_ssh_port)"
  if [[ "$custom" == true ]]; then
    W_SSH_PORT="$(wizard_prompt_default "SSH 端口" "$current_port")"
  else
    W_SSH_PORT="$current_port"
    echo "SSH 端口：$W_SSH_PORT（沿用当前连接）"
  fi
  [[ "$W_SSH_PORT" =~ ^[0-9]+$ ]] && ((W_SSH_PORT>=1 && W_SSH_PORT<=65535)) || die "SSH 端口无效。"
  wizard_collect_ssh_key

  W_ROOT_DOMAIN=""; W_LE_EMAIL=""
  if [[ "$W_PROFILE" == "nginx-reality" || "$W_PROFILE" == "lucky-reality" ]]; then
    echo
    while [[ -z "$W_ROOT_DOMAIN" ]]; do
      W_ROOT_DOMAIN="$(wizard_prompt_default "Cloudflare 根域名（例如 example.com）" "")"
      [[ "$W_ROOT_DOMAIN" != *://* && "$W_ROOT_DOMAIN" != */* && "$W_ROOT_DOMAIN" == *.* ]] || { echo "请只填写根域名，不要带 https:// 或路径。"; W_ROOT_DOMAIN=""; }
    done
    W_LE_EMAIL="$(wizard_prompt_default "Let's Encrypt 邮箱（可留空）" "")"
  fi

  W_REALITY_TARGET_MODE="auto"; W_REALITY_TARGET=""
  if [[ "$W_PROFILE" != "base-only" && "$custom" == true ]]; then
    local target_choice
    target_choice="$(wizard_select "Reality Target：" "自动检测并推荐（推荐）" "手动填写")"
    if [[ "$target_choice" == 2 ]]; then
      W_REALITY_TARGET_MODE="manual"
      while [[ -z "$W_REALITY_TARGET" ]]; do W_REALITY_TARGET="$(wizard_prompt_default "Reality Target，例如 www.microsoft.com:443" "")"; done
    fi
  fi

  W_PANEL_PATH="/zhg/"
  W_SUB_PATH="/zhg/"
  W_SUBSCRIPTION_PORT="2096"
  W_ENABLE_DOCKER="false"
  if [[ "$custom" == true && "$W_PROFILE" != "base-only" ]]; then
    W_PANEL_PATH="$(normalize_path "$(wizard_prompt_default "3x-ui 面板 URI Path" "/zhg/")")"
    local sub_input
    sub_input="$(wizard_prompt_default "订阅 URI Path" "/zhg/")"
    W_SUB_PATH="$(normalize_path "$sub_input")"
    W_SUBSCRIPTION_PORT="$(wizard_prompt_default "3x-ui Subscription 内部/直连端口" "2096")"
    [[ "$W_SUBSCRIPTION_PORT" =~ ^[0-9]+$ ]] && ((W_SUBSCRIPTION_PORT>=1 && W_SUBSCRIPTION_PORT<=65535)) || die "订阅端口无效。"
  fi
  if [[ "$custom" == true ]]; then
    if wizard_yesno "同时安装 Docker Engine/Compose？" n; then W_ENABLE_DOCKER="true"; fi
  fi

  echo
  echo "---------------- 部署摘要 ----------------"
  echo "Profile           : $W_PROFILE"
  echo "IPv4              : $W_SERVER_IP"
  echo "SSH Port          : $W_SSH_PORT"
  [[ -n "$W_ROOT_DOMAIN" ]] && echo "Root Domain       : $W_ROOT_DOMAIN"
  if [[ "$W_PROFILE" != "base-only" ]]; then
    echo "Panel URI         : $W_PANEL_PATH"
    echo "Subscription URI  : $W_SUB_PATH"
    echo "Subscription Port : $W_SUBSCRIPTION_PORT"
    echo "Reality Target    : ${W_REALITY_TARGET_MODE}${W_REALITY_TARGET:+ ($W_REALITY_TARGET)}"
    echo "Clash/Mihomo      : ON / Routing ON / Auto Detect ON / (?i)(clash|mihomo)"
  fi
  echo "Docker            : $W_ENABLE_DOCKER"
  echo "------------------------------------------"
  wizard_yesno "确认并开始部署？" y || return 10
}

wizard_run() {
  local cfg="${1:-$PERSIST_DIR/config.env}"
  ensure_dir "$(dirname "$cfg")"
  wizard_collect || return $?
  wizard_write_config "$cfg"
  log_ok "配置已生成：$cfg"
  "$ROOT_DIR/vps-init" apply "$cfg"
}
